### PR TITLE
2.25 eye see tea add pull of events by program and organisation unit

### PR DESCRIPTION
**Pull request by idelcano**
Added: Pull of events by orgunit and program.

### CODE REVIEW

**Comment by idelcano** [comment]
it is true, but they are using the models and not only the uid strings, for
expample in the list method. i think we should continue in the same way.
What do you think?

**Comment by xurxodev** [comment]
@idelcano I think that for pull events (API) they only use uids and for list (DB) they use models

**Comment by idelcano** [comment]
@xurxodev  it is ready

**Comment by idelcano** [comment]
@xurxodev is ready to work with the new pull.

I added a sync strategy on the pull called NO_DELETE
This SyncStrategy avoid retrieving all the ids  because it is only necessary if we want delete rows.

**Pull request closed without merging**
