### PR TITLE
Added new types time, datetime, and url

### PR DESCRIPTION
**Pull request by idelcano**
Closes https://github.com/EyeSeeTea/dhis2-android-eventcapture/issues/90

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
@idelcano When I create a new event for a program with url dataElement then this field show invalid url, I think that validation should start when user type the value as in web

**Comment by idelcano** [comment]
Done!

**Review by xurxodev — CHANGES_REQUESTED** [review]
@idelcano Ok now the first time when the field is empty invalid URL message is not shown but there is a problem:
- If I type an invalid URL as http://url.comgggg I can save the event and on the web, this is not possible
- if I sync this event with the wrong URL server return a conflict

{"httpStatus":"Conflict","httpStatusCode":409,"status":"WARNING","message":"One more conflicts encountered, please check import summary.","response":{"responseType":"ImportSummary","status":"WARNING","importOptions":{"idSchemes":{},"dryRun":false,"async":false,"importStrategy":"CREATE_AND_UPDATE","mergeMode":"REPLACE","skipExistingCheck":false,"sharing":false,"skipNotifications":false,"datasetAllowsPeriods":false,"strictPeriods":false,"strictCategoryOptionCombos":false,"strictAttributeOptionCombos":false,"strictOrganisationUnits":false,"requireCategoryOptionCombo":false,"requireAttributeOptionCombo":false},"importCount":{"imported":0,"updated":0,"ignored":1,"deleted":0},"conflicts":[{"object":"vHrMSIgETVh","value":"value_not_url"}],"reference":"fyV2EhLKdeU"}}

**Comment by idelcano** [comment]
@xurxodev  done.

The URL question type have two validation, the web validation [dhis-core link](https://github.com/dhis2/dhis2-core/blob/3ced395633a1f3fe83d678fff76fb97e5f2d7010/dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/ValidationUtils.java#L172) , and a new api validation in 2.29.

I talked with @ifoche  and we can use the api validation, it´s most restrictive and is not a reg exp like in the web app, but is a apache validation and looks better.

To save the url type in 2.29 you maybe will need add the "ALL" permission to write the category option in the user role Data Entry Clerk
(I used "contraceptives voucher program" and "Voucher htc" and i needed it)

Finally, i didn't change the workflow when the user write a invalid url. 
If the event has a valid saved value and change by a wrong value, when you go back the event save the last valid value.

Note: When you test the web app is better check the events using the api /api/events/uid. because when you fill a event and go back, the webapp shows you the cached value but isn't in the server.

**Review by xurxodev — APPROVED** [review]
thanks @idelcano

**Pull request merged**
