### PR TITLE
Feature introduce translations

### LINKED ISSUE #278: Introduce translations

### PR DESCRIPTION
**Pull request by Amejia481**
Close #278

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
@Amejia481 Please can you refactor all calls to has xxQuery parameter that encapsulates parameters As isTranslationOn, translationLocale, uids ... and create it if there are not exists? I think maybe interesting create a Query base class with language parameters so inherits from it all specific queries

**Review by xurxodev — CHANGES_REQUESTED** [review]
Can @Amejia481  review the next things:
- Travis compilation is failing in your last commit
- Merge development branch in this branch because there are many conflicts and now exists new endpoint calls for DataElement, TrackedentityAttribute, RelationshipType and we need to add language parameters also

**Review by xurxodev — APPROVED** [review]
thanks @Amejia481, please review my changes and let me know if you have some doubts

**Comment by Amejia481** [comment]
:+1:

**Pull request merged**
