### PR TITLE
Feature sync stop on wrong events fk

### LINKED ISSUE #324: sync stops on wrong server data
On a SQLiteConstraintException data sync stops. Aparently, when the server provides you with wrong data (e.g. an event that comes without OU), the exception is launched and sync stops there. To test it, sync with android to android-current server.

### PR DESCRIPTION
**Pull request by idelcano**
Closes #324 
Fixed: The sync don't stop on event/trackedEntityDataValue foreign key exception.
Solved issues #313 and #298

### CODE REVIEW

**Comment by xurxodev** [comment]
@idelcano If this issue resolved #313 and #298, should these issues close your PR and be related to this?

**Review by xurxodev — CHANGES_REQUESTED** [review]
@idelcano seems that this solution work but I have some changes to realize in this PR:
- can you try to make nested transactions? (one for page and one for event) so that only one disk access for each page of events continues
- would be interesting that the test rollback_transaction_when_insert_a_event_with_wrong_foreign_key should validate almost two events, one valid and one with conflict and verify that valid is persisted in database
- I think is necessary realize a migration becuase we are modifying database structure
- please if this PR solved other issues, close these PR and link to this

**Comment by idelcano** [comment]
> nested transactions

I couldn't do it.

> would be interesting that the test rollback_transaction_when_insert_a_event_with_wrong_foreign_key should validate almost two events, one valid and one with conflict and verify that valid is persisted in database

Done

> I think is necessary realize a migration becuase we are modifying database structure

Done


> please if this PR solved other issues, close these PR and link to this


Done

**Review by xurxodev — CHANGES_REQUESTED** [review]
@idelcano there are two tests is failing in EventPostCallRealIntegrationShould, can you review it, please?

**Review by xurxodev — APPROVED** [review]
thanks @idelcano

**Pull request merged**
