### PR TITLE
Add orgunit attributevalue

### LINKED ISSUE #11: Add OrgUnit Attributes

### PR DESCRIPTION
**Pull request by idelcano**
Closes #11

This branch needs the dhis_attributes_compatibility branch in malariapp for compile(becouse malariapp use AttributeValues$table in some places, and AttributeValues was removed).

### CODE REVIEW

**Comment by idelcano** [comment]
closses #11

**Comment by ifoche** [comment]
I think that, in order to make waffle understand that "closes (number)" it has to be in the description of the issue, not in a normal comment. Let me move it for you to show you what I'm saying

**Comment by adrianq** [comment]
I think it has to be in a commit comment and it doesn't close the issue until the bit of code gets into the master branch

**Comment by ifoche** [comment]
Yes, that's for making the commit to trigger the automatic close of the issue, but what @idelcano was trying to do is what waffle does, it puts together the PR and the issue it references when you put in the description of the PR 'Closes (number)' where number is the number of the issue

**Comment by ifoche** [comment]
@idelcano the first test I've done with this PR doesn't to be ok. It was supposed to introduced OrgUnit attributes and, if I'm not bad, I had added for you the Productivity orgUnit attribute with H value in the case of test facility 1 and L value for test facility 2. Please see in attached image how I'm getting different productivities for test facility 1 and 2. Is this still mocked-up? 

productivity_bug

**Comment by idelcano** [comment]
The workflow is: in the migration of our db the default productivity is L. After pull is H for test facility 2 and L fot test facility 1. Are you trying with this branch and with the malariaapp branch? I will check it.

**Comment by ifoche** [comment]
yes, I'm using add_orgunit_attributevalue in sdk and add_dialog_compulsory_survey in malariapp, both updated with last changes in their respective 2.22 and development branch (you can pull the differences, but are changes that don't affect this part in principle). Please let me know if you find any problem reproducing it.

**Comment by idelcano** [comment]
Ok, i dont find that bug, one thing. In dev-ci the test 1 is H and the test 2 is L, in dev-staging we not have the org unit attribute set.
Anyway, i create a migration, in this migration the orgunit adds the production column, and set by default to low productivity. I don´t understad how you can have diferent productivity.

**Comment by ifoche** [comment]
@idelcano I'm always checking against dev-ci, so it's not that, and I'm reinstalling the app from 0, so table migration shouldn't be affecting either...so you don't get the same result? let me recheck, just in case...

**Comment by ifoche** [comment]
@idelcano the branch in malariapp repo is not add_dialog_compulsory_survey but dhis_attributes_compatibility, that was the mistake I think. Let me recheck

**Comment by ifoche** [comment]
yes, that's it. Everything ok, sorry and thank you for wasting time checking

**Comment by idelcano** [comment]
Sorry for my fault too, i didnt read when you said you are in the wrong branch

**Comment by ifoche** [comment]
Congratulations @idelcano. I've seen the code very clean here and even ready for an external PR. Thank you very much for this

**Pull request merged**
