### PR TITLE
Retrieve all org units parameters

### LINKED ISSUE #19: Retrieve all OrgUnits parameters
The SDK is currently downloading just a few parameters for each OrgUnit. We need to add columns in the SDK DB to hold all the OrtUnit parameters that we've actually available in the json answer to the API call

### PR DESCRIPTION
**Pull request by idelcano**
closes #19 

@ifoche ! 
Only one thing.
I was setting the ancestors and the childrens as lists before ask and read your anwser. Should i remove it? You said me not touch it. But i was storing it before.
Thanks.

### CODE REVIEW

**Comment by ifoche** [comment]
Let's hear @ivanarrizabalaga . @ivanarrizabalaga did you already have that part implemented? If you haven't, can you confirm that you can merge to your branch Ina's solution and build yours on top of it? Otherwise, @idelcano, I guess you should remove it from your PR.

**Comment by idelcano** [comment]
@ifoche , i only added the list of ancesors and children like in  https://hnqis-dev-staging.psi-mis.org/api/organisationUnits/QS7sK8XzdQc?fields=[%3Aall] not the orgunitlevels.

**Comment by ifoche** [comment]
@idelcano yes, but @ivanarrizabalaga needs that list of children and ancestors to build the orgUnit dependency tree, so I don't know if he's already added it by himself. The orgUnitLevels doesn't provide by themselves all the information to build the hierarchy of the orgUnitLevels

**Comment by idelcano** [comment]
I added the new tables in the wipe() in the last commit (the old metadata is not erased without it).

**Comment by ifoche** [comment]
@ivanarrizabalaga, did you see this issue? As you're working in the tests I imagine that you don't collide with @idelcano and he can just keep this PR as is but, can you confirm?

**Comment by idelcano** [comment]
@ifoche i did a revert in [https://github.com/EyeSeeTea/dhis2-android-sdk/commit/defd12c1ee5e3afe58532c2ff6cfc320445a0ef5](defd12c)
I did refactor getOrganistationUnitAttributeValues to getOrganistationUnit here: [https://github.com/EyeSeeTea/dhis2-android-sdk/commit/a5f6b83b84e6084e63f47816e01f96586ccf27f2](a5f6b83)
And i fixed typo organistation to organisation in 
[https://github.com/EyeSeeTea/dhis2-android-sdk/commit/267ae04e63ab70bd46ff31e086c836f878c8377c](267ae04)

I worry becouse i don´t be sure if it is ok...

**Comment by ifoche** [comment]
Thank you, I'll cherry-pick it tonight, so I'll tell you more if I find any problem

**Comment by ifoche** [comment]
Ok, I've tested cherry picking them, and there's no way to do it, as there are other changes there (i.e. QUERY_MAP_FULL) that depends on future changes. I'm going to simply rename the function manually...although that will suppose a future conflict

**Comment by ifoche** [comment]
ok, finally I manage to pick your changes and do a merge that I think is properly done. thank you @idelcano, it is now uploaded to the branch used for the PR

**Pull request merged**
